plugins { id 'com.android.application' }

android {
    namespace 'ai.ayurones.vm'
    compileSdk 36
    defaultConfig {
        applicationId 'ai.ayurones.vm'
        minSdk 26
        targetSdk 36
        versionCode 50
        versionName '0.5.0'
    }
    androidResources {
        noCompress += ['ayr']
    }
    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}