package ai.ttauoi.mod;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.widget.*;import java.util.*;
public class MainActivity extends Activity{
 static final String V="v2.0.5"; SharedPreferences p; LinearLayout list;
 int d(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.BLACK);v.setPadding(d(18),d(14),d(18),d(14));return v;}
 Button b(String s){Button v=new Button(this);v.setText(s);v.setAllCaps(false);return v;}
 public void onCreate(Bundle x){super.onCreate(x);p=getSharedPreferences("ttauoi",0);privacy();}
 void page(String title){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(Color.WHITE);TextView h=t(title,20);h.setTextColor(Color.WHITE);h.setBackgroundColor(Color.BLACK);r.addView(h,new LinearLayout.LayoutParams(-1,d(58)));ScrollView s=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(d(10),d(10),d(10),d(24));s.addView(list);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);}
 void privacy(){page("Профиль  ›  Конфиденциальность");list.addView(t("Конфиденциальность",26));list.addView(t("Настройки аккаунта и дополнительные параметры",14));Button m=b("⚙  Мод");m.setTextSize(18);m.setOnClickListener(v->mod());list.addView(m,new LinearLayout.LayoutParams(-1,d(58)));}
 void mod(){page("TTAuOI  ·  Мод");list.addView(t("TikTok AUOI (TTAuOI)   "+V,24));Button tg=b("TTAuOI Telegram Channel");tg.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://t.me/TTAuOI"))));list.addView(tg);list.addView(t("Подмена региона",19));Button r=b("Регион: "+p.getString("region",Locale.getDefault().getCountry()));r.setOnClickListener(v->region(r));list.addView(r);list.addView(t("Фильтрация контента",19));slider("Минимум лайков","likes",1000000);slider("Минимум просмотров","views",10000000);slider("Максимальный возраст видео, дней","days",3650);sw("Убрать трансляции","live");sw("Убрать рекламу","ads");sw("Убрать фотографии из ленты","feedphotos");sw("Убрать фотографии из историй","storyphotos");list.addView(t("Внешний вид",19));list.addView(t("Цвет интерфейса — 10 вариантов",15));String[] n={"Красный","Розовый","Фиолетовый","Синий","Голубой","Бирюзовый","Зелёный","Оранжевый","Жёлтый","Белый"};int[] c={0xFFFE2C55,0xFFFF4FA3,0xFF8E44FF,0xFF3478F6,0xFF00AEEF,0xFF00BFA5,0xFF20A05A,0xFFFF7A00,0xFFFFB800,0xFF555555};for(int i=0;i<10;i++){Button q=b(n[i]);final int col=c[i];q.setTextColor(Color.WHITE);q.setBackgroundColor(col);q.setOnClickListener(v->{p.edit().putInt("color",col).apply();restartPrompt();});list.addView(q,new LinearLayout.LayoutParams(-1,d(44)));}list.addView(t("Версия мода: "+V,14));list.addView(t("Настройки сохраняются локально. Подключение к конкретной сборке TikTok требует отдельного совместимого интеграционного слоя.",12));}
 void region(Button r){String[] iso=Locale.getISOCountries();ArrayList<String>a=new ArrayList<>();for(String c:iso){Locale l=new Locale("",c);a.add(c+" — "+l.getDisplayCountry(Locale.getDefault()));}Collections.sort(a);String[] z=a.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Выберите регион").setItems(z,(d,w)->{String c=z[w].substring(0,2);p.edit().putString("region",c).apply();r.setText("Регион: "+c);restartPrompt();}).show();}
 void slider(String name,String key,int max){TextView l=t(name+" ["+p.getInt(key,0)+"]",15);list.addView(l);SeekBar s=new SeekBar(this);s.setMax(1000);s.setProgress((int)((long)p.getInt(key,0)*1000/max));s.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar x,int q,boolean f){int v=(int)((long)q*max/1000);l.setText(name+" ["+v+"]");p.edit().putInt(key,v).apply();}public void onStartTrackingTouch(SeekBar x){}public void onStopTrackingTouch(SeekBar x){restartPrompt();}});list.addView(s);}
 void sw(String name,String key){Switch s=new Switch(this);s.setText(name);s.setChecked(p.getBoolean(key,false));s.setPadding(d(8),d(8),d(8),d(8));s.setOnCheckedChangeListener((v,c)->{p.edit().putBoolean(key,c).apply();restartPrompt();});list.addView(s);}
 void restartPrompt(){new AlertDialog.Builder(this).setTitle("Перезагрузить приложение").setMessage("Изменения сохранены. Перезапустите приложение, чтобы применить настройки.").setPositiveButton("Перезапустить",(d,w)->{finishAffinity();startActivity(new Intent(this,MainActivity.class));}).setNegativeButton("Позже",null).show();}
}