package ai.ayurones.vm;

import java.util.*;

public final class CommandCatalog {
    public static final class Command {
        public final String name;
        public final String description;
        public final String target;
        Command(String name,String description,String target){this.name=name;this.description=description;this.target=target;}
    }
    private static final LinkedHashMap<String,Command> COMMANDS=new LinkedHashMap<>();
    static {
        add("fs.pwd","Показать текущую гостевую папку","pwd");
        add("fs.list","Показать файлы и каталоги","ls -la");
        add("fs.tree","Показать дерево файлов","find . -maxdepth 3 -print");
        add("fs.stat","Показать сведения о файлах","stat");
        add("fs.mkdir","Создать каталог","mkdir");
        add("fs.touch","Создать пустой файл","touch");
        add("fs.read","Прочитать файл","cat");
        add("fs.head","Показать начало файла","head");
        add("fs.tail","Показать конец файла","tail");
        add("fs.count","Подсчитать строки/слова/байты","wc");
        add("fs.grep","Найти текст в файлах","grep -n");
        add("fs.find","Найти файлы","find .");
        add("fs.size","Показать размеры","du -sh");
        add("fs.disk","Показать место в файловой системе","df -h .");
        add("fs.copy","Скопировать файл","cp");
        add("fs.move","Переместить файл","mv");
        add("fs.remove","Удалить файл или каталог","rm -rf");
        add("fs.rmdir","Удалить пустой каталог","rmdir");
        add("fs.basename","Получить имя файла","basename");
        add("fs.dirname","Получить каталог пути","dirname");
        add("fs.link","Прочитать ссылку","readlink");
        add("fs.sort","Сортировать строки","sort");
        add("fs.uniq","Убрать повторяющиеся строки","uniq");
        add("fs.cut","Вырезать поля/символы","cut");
        add("fs.translate","Заменить или удалить символы","tr");
        add("text.echo","Вывести текст","echo");
        add("text.printf","Форматированный вывод","printf");
        add("text.sed","Потоковое редактирование текста","sed");
        add("text.awk","Обработка текста по полям","awk");
        add("text.grep","Поиск по тексту","grep");
        add("text.head","Первые строки","head");
        add("text.tail","Последние строки","tail");
        add("text.lines","Нумерованные строки","nl");
        add("text.fold","Перенос длинных строк","fold");
        add("text.format","Форматирование абзацев","fmt");
        add("text.reverse","Развернуть строки","rev");
        add("text.translate","Преобразовать символы","tr");
        add("text.columns","Выбрать колонки","cut");
        add("text.paste","Объединить строки","paste");
        add("text.join","Соединить таблицы по ключу","join");
        add("text.diff","Сравнить текст","diff");
        add("text.compare","Сравнить байты","cmp");
        add("text.strings","Извлечь читаемые строки","strings");
        add("text.encode","Кодировать Base64","base64");
        add("text.md5","Посчитать MD5","md5sum");
        add("text.sha256","Посчитать SHA-256","sha256sum");
        add("text.args","Передать аргументы пакетно","xargs");
        add("text.repeat","Повторить вывод","yes");
        add("text.sequence","Создать последовательность","seq");
        add("text.calculate","Простое выражение","expr");
        add("sys.id","Информация о UID/GID","id");
        add("sys.uname","Информация о ядре","uname -a");
        add("sys.props","Системные свойства гостя","getprop");
        add("sys.date","Текущая дата и время","date");
        add("sys.uptime","Время работы процесса","uptime");
        add("sys.processes","Список процессов","ps");
        add("sys.whoami","Текущий пользователь","whoami");
        add("sys.env","Переменные окружения","env");
        add("sys.printenv","Показать переменные","printenv");
        add("sys.cwd","Текущий путь","pwd");
        add("sys.uid","UID процесса","id -u");
        add("sys.gid","GID процесса","id -g");
        add("sys.config","Сведения о конфигурации","getconf");
        add("sys.storage","Сводка хранилища","df -h");
        add("sys.mounts","Список подключений","mount");
        add("sys.kernel","Версия ядра","cat /proc/version");
        add("sys.cpu","Информация о CPU","cat /proc/cpuinfo");
        add("sys.memory","Информация о памяти","cat /proc/meminfo");
        add("sys.timers","Сведения о времени работы","cat /proc/uptime");
        add("sys.load","Средняя нагрузка","cat /proc/loadavg");
        add("sys.status","Статус текущего процесса","cat /proc/self/status");
        add("sys.devices","Список устройств","ls -la /dev");
        add("sys.sysfs","Обзор sysfs","ls -la /sys");
        add("sys.procfs","Обзор procfs","ls -la /proc");
        add("sys.toybox","Версия встроенных утилит","toybox");
        add("proc.list","Список процессов","ps");
        add("proc.top","Сводка процессов","top -n 1");
        add("proc.pidof","Найти PID по имени","pidof");
        add("proc.kill","Отправить сигнал процессу","kill");
        add("proc.killall","Остановить процессы по имени","killall");
        add("proc.jobs","Список фоновых задач","jobs");
        add("proc.pgrep","Поиск PID","pgrep");
        add("proc.pkill","Сигнал процессам по имени","pkill");
        add("proc.wait","Ожидание процесса","wait");
        add("proc.sleep","Пауза","sleep");
        add("proc.nice","Запустить с приоритетом","nice");
        add("proc.renice","Изменить приоритет","renice");
        add("proc.chrt","Параметры планировщика","chrt");
        add("proc.taskset","Маска CPU","taskset");
        add("proc.time","Измерить время команды","time");
        add("proc.timeout","Ограничить время команды","timeout");
        add("proc.nohup","Запуск без терминала","nohup");
        add("proc.setsid","Новая сессия","setsid");
        add("proc.shell","Запустить POSIX shell","sh");
        add("proc.ash","Запустить ash","ash");
        add("proc.mksh","Запустить mksh","mksh");
        add("proc.true","Всегда успешный код","true");
        add("proc.false","Всегда код ошибки","false");
        add("proc.test","Проверка условия","test");
        add("proc.expr","Вычислить выражение","expr");
        add("net.interfaces","Сетевые интерфейсы","ip addr");
        add("net.routes","Таблица маршрутов","ip route");
        add("net.sockets","Список сокетов","ss -lntup");
        add("net.ping","Проверка доступности узла","ping");
        add("net.dns","Проверка DNS","nslookup");
        add("net.http","HTTP-запрос","curl");
        add("net.download","Загрузка по URL","wget");
        add("net.netstat","Сетевая статистика","netstat -an");
        add("net.ifconfig","Сведения об интерфейсах","ifconfig");
        add("net.hostname","Имя узла","hostname");
        add("net.route","Маршруты","route -n");
        add("net.arp","ARP-таблица","arp -n");
        add("net.tcp","TCP-соединения","cat /proc/net/tcp");
        add("net.udp","UDP-соединения","cat /proc/net/udp");
        add("net.dev","Сетевые устройства","ls -la /sys/class/net");
        add("net.wifi","Свойства Wi‑Fi в системе","getprop | grep -i wifi");
        add("net.dnsprops","DNS-свойства","getprop | grep -i dns");
        add("net.connectivity","Сведения о connectivity","getprop | grep -i connectivity");
        add("net.proxy","Сведения о proxy","getprop | grep -i proxy");
        add("net.gateway","Поиск шлюза","ip route | grep default");
        add("net.addresses","Адреса хоста","ip addr show");
        add("net.neighbors","Соседи сети","ip neigh");
        add("net.stats","Статистика интерфейсов","cat /proc/net/dev");
        add("net.tcp6","IPv6 TCP-сокеты","cat /proc/net/tcp6");
        add("net.udp6","IPv6 UDP-сокеты","cat /proc/net/udp6");
        add("arch.tar","Работа с TAR-архивом","tar");
        add("arch.gzip","Сжать gzip","gzip");
        add("arch.gunzip","Распаковать gzip","gunzip");
        add("arch.zip","Создать ZIP","zip");
        add("arch.unzip","Распаковать ZIP","unzip");
        add("arch.cpio","Работа с CPIO","cpio");
        add("arch.xz","Сжатие XZ","xz");
        add("arch.bzip2","Сжатие bzip2","bzip2");
        add("arch.bzcat","Читать bzip2","bzcat");
        add("arch.zcat","Читать gzip","zcat");
        add("arch.base64","Base64 кодирование","base64");
        add("arch.md5","MD5 контрольная сумма","md5sum");
        add("arch.sha256","SHA-256 контрольная сумма","sha256sum");
        add("arch.cmp","Сравнить файлы","cmp");
        add("arch.diff","Сравнить каталоги/файлы","diff");
        add("arch.split","Разделить файл","split");
        add("arch.cat","Склеить/прочитать байты","cat");
        add("arch.dd","Копировать блоки данных","dd");
        add("arch.od","Показать восьмеричный дамп","od");
        add("arch.hexdump","Показать hex-дамп","hexdump");
        add("arch.strings","Извлечь строки","strings");
        add("arch.file","Определить тип файла","file");
        add("arch.stat","Метаданные файла","stat");
        add("arch.du","Размеры каталогов","du -sh");
        add("arch.packlist","Список файлов для упаковки","find . -type f");
        add("user.whoami","Имя текущего пользователя","whoami");
        add("user.id","UID и группы","id");
        add("user.groups","Группы процесса","id -Gn");
        add("user.env","Переменные окружения","env");
        add("user.printenv","Вывести окружение","printenv");
        add("user.umask","Текущая маска прав","umask");
        add("user.home","Домашний путь процесса","printf '%s\\n' \"$HOME\"");
        add("user.files","Содержимое guest/files","ls -la files");
        add("user.cache","Содержимое guest/cache","ls -la cache");
        add("user.tmp","Содержимое guest/tmp","ls -la tmp");
        add("user.config","Содержимое guest/config","ls -la config");
        add("user.data","Содержимое guest/data","ls -la data");
        add("user.logs","Содержимое guest/logs","ls -la logs");
        add("user.shared","Содержимое guest/shared","ls -la shared");
        add("user.permissions","Права текущего каталога","ls -ld .");
        add("user.owner","Владелец текущего каталога","stat -c '%U:%G' .");
        add("user.numericid","Числовой UID","id -u");
        add("user.numericgid","Числовой GID","id -g");
        add("user.groupsid","Числовые группы","id -G");
        add("user.shell","Текущая оболочка","printf '%s\\n' \"$SHELL\"");
        add("user.path","PATH","printf '%s\\n' \"$PATH\"");
        add("user.lang","Язык среды","printf '%s\\n' \"$LANG\"");
        add("user.timezone","Часовой пояс","date +%Z");
        add("user.locale","Locale","printf '%s\\n' \"$LANG\"");
        add("user.limits","Ограничения процесса","cat /proc/self/limits");
        add("package.list","Список гостевых пакетов (если доступен)","pm list packages");
        add("package.path","Путь пакета","pm path");
        add("package.info","Информация о пакете","pm dump");
        add("package.install","Установка APK в гостевую среду","pm install");
        add("package.uninstall","Удаление гостевого пакета","pm uninstall");
        add("package.clear","Очистка данных пакета","pm clear");
        add("package.enable","Включение пакета","pm enable");
        add("package.disable","Отключение пакета","pm disable-user");
        add("package.resolve","Разрешение пакета","cmd package resolve-activity");
        add("package.features","Функции Android package manager","pm list features");
        add("package.permissions","Разрешения пакетов","pm list permissions");
        add("package.users","Пользователи пакетного менеджера","pm list users");
        add("package.libraries","Библиотеки","pm list libraries");
        add("package.instrumentation","Инструментирование","pm list instrumentation");
        add("package.services","Сервисы пакета","cmd package query-services");
        add("package.receivers","Broadcast receivers","cmd package query-receivers");
        add("package.providers","Content providers","cmd package query-content-providers");
        add("package.activities","Activities","cmd package query-activities");
        add("package.apex","APEX-модули","pm list packages --apex");
        add("package.system","Системные пакеты","pm list packages -s");
        add("package.thirdparty","Сторонние пакеты","pm list packages -3");
        add("package.uid","Пакеты по UID","pm list packages --uid");
        add("package.installer","Источник установки","pm get-install-location");
        add("package.verify","Состояние package manager","cmd package help");
        add("package.help","Справка package manager","cmd package help");
        add("vm.info","Показать информацию гостевой среды","echo Ayurones VM guest");
        add("vm.version","Показать выбранную версию Android","cat .prepare_* 2>/dev/null");
        add("vm.status","Показать состояние подготовки","ls -la .prepare_* 2>/dev/null");
        add("vm.storage","Размер гостевого каталога","du -sh .");
        add("vm.files","Список гостевой системы","find . -maxdepth 2 -print");
        add("vm.reset","Подготовить чистый каталог","echo guest reset requested");
        add("vm.home","Открыть домашнюю структуру","ls -la");
        add("vm.system","Показать системные файлы","find . -maxdepth 2 -name 'system_*' -print");
        add("vm.markers","Показать маркеры среды","find . -maxdepth 1 -name '.*' -print");
        add("vm.uid","Показать UID гостя","id -u");
        add("vm.sandbox","Показать корень sandbox","pwd");
        add("vm.arch","Архитектура гостя","uname -m");
        add("vm.api","Показать Android API хоста","getprop ro.build.version.sdk");
        add("vm.device","Модель устройства","getprop ro.product.model");
        add("vm.brand","Бренд устройства","getprop ro.product.brand");
        add("vm.release","Версия Android хоста","getprop ro.build.version.release");
        add("vm.abis","Поддерживаемые ABI","getprop ro.product.cpu.abilist");
        add("vm.kernel","Версия ядра","uname -r");
        add("vm.props","Гостевые свойства","getprop");
        add("vm.environment","Переменные гостя","env");
        add("vm.process","PID текущей оболочки","echo $$");
        add("vm.cwd","Текущая папка гостя","pwd");
        add("vm.disk","Место гостя","df -h .");
        add("vm.memory","Память процесса","cat /proc/self/status | grep -E 'VmPeak|VmSize|VmRSS'");
        add("vm.diagnose","Быстрая диагностика","id; uname -a; df -h .");
        add("dev.debug","Быстрый debug-вывод","echo debug");
        add("dev.trace","Тест трассировки","echo trace");
        add("dev.env","Окружение разработчика","env");
        add("dev.props","Android properties","getprop");
        add("dev.logs","Локальный logcat","logcat -d -t 100");
        add("dev.logclear","Очистить доступный log buffer","logcat -c");
        add("dev.shell","Проверить оболочку","sh -c 'echo shell-ok'");
        add("dev.commands","Проверить каталог команд","echo 'Use help to list commands'");
        add("dev.path","Пути утилит","printf '%s\\n' \"$PATH\"");
        add("dev.version","Версии основных утилит","sh --version 2>&1 | head");
        add("dev.java","Версия Java внутри окружения","java -version");
        add("dev.python","Проверить Python","python --version");
        add("dev.node","Проверить Node.js","node --version");
        add("dev.perl","Проверить Perl","perl -v");
        add("dev.ruby","Проверить Ruby","ruby --version");
        add("dev.git","Проверить Git","git --version");
        add("dev.sqlite","Проверить SQLite","sqlite3 --version");
        add("dev.openssl","Проверить OpenSSL","openssl version");
        add("dev.busybox","Проверить BusyBox","busybox --help");
        add("dev.toybox","Проверить Toybox","toybox --help");
        add("dev.which","Найти исполняемый файл","which");
        add("dev.whereis","Найти программу","whereis");
        add("dev.command","Проверить shell command","command -v");
        add("dev.alias","Список shell aliases","alias");
        add("dev.builtins","Список shell builtins","help");
        add("data.cat","Прочитать данные","cat");
        add("data.head","Начало данных","head");
        add("data.tail","Конец данных","tail");
        add("data.wc","Размер текста","wc");
        add("data.sort","Сортировка","sort");
        add("data.uniq","Уникальные строки","uniq");
        add("data.cut","Выбор полей","cut");
        add("data.tr","Замена символов","tr");
        add("data.sed","Редактирование потока","sed");
        add("data.awk","Анализ полей","awk");
        add("data.grep","Фильтрация","grep");
        add("data.paste","Объединение колонок","paste");
        add("data.join","Соединение таблиц","join");
        add("data.split","Разбиение файла","split");
        add("data.base64","Base64","base64");
        add("data.md5","MD5","md5sum");
        add("data.sha256","SHA-256","sha256sum");
        add("data.od","Дамп данных","od");
        add("data.strings","Строки из бинарных данных","strings");
        add("data.cmp","Побайтовое сравнение","cmp");
        add("data.diff","Сравнение содержимого","diff");
        add("data.json","Фильтр JSON через системные инструменты","cat");
        add("data.csv","Просмотр CSV","cat");
        add("data.hex","HEX-представление","hexdump");
        add("data.bytes","Просмотр байтов","od -An -tx1");
        add("time.now","Текущее время","date");
        add("time.date","Дата","date +%F");
        add("time.clock","Часы с секундами","date +%T");
        add("time.iso","ISO-время","date -Iseconds");
        add("time.unix","Unix timestamp","date +%s");
        add("time.zone","Часовой пояс","date +%Z");
        add("time.offset","Смещение часового пояса","date +%z");
        add("time.year","Текущий год","date +%Y");
        add("time.month","Текущий месяц","date +%m");
        add("time.day","Текущий день","date +%d");
        add("time.weekday","День недели","date +%A");
        add("time.week","Номер недели","date +%V");
        add("time.uptime","Uptime","uptime");
        add("time.sleep1","Пауза 1 секунда","sleep 1");
        add("time.sleep5","Пауза 5 секунд","sleep 5");
        add("time.sleep10","Пауза 10 секунд","sleep 10");
        add("time.timer","Секундомер shell","date +%s");
        add("time.epochms","Epoch в миллисекундах","date +%s%3N");
        add("time.calendar","Календарь месяца","cal");
        add("time.measure","Измерить команду","time");
        add("time.deadline","Ограничить время","timeout");
        add("time.elapsed","Показать uptime-счётчик","cat /proc/uptime");
        add("time.monotonic","Монотонный счётчик","cat /proc/uptime");
        add("time.boot","Время загрузки по uptime","cat /proc/uptime");
        add("time.timezonefile","Проверить timezone data","ls -la /system/usr/share/zoneinfo 2>/dev/null");
        add("math.add","Сложение","expr");
        add("math.subtract","Вычитание","expr");
        add("math.multiply","Умножение","expr");
        add("math.divide","Деление","expr");
        add("math.mod","Остаток деления","expr");
        add("math.compare","Сравнение чисел","expr");
        add("math.max","Максимум через awk","awk");
        add("math.min","Минимум через awk","awk");
        add("math.sum","Сумма через awk","awk");
        add("math.avg","Среднее через awk","awk");
        add("math.abs","Абсолютное значение","awk");
        add("math.round","Округление через awk","awk");
        add("math.sqrt","Квадратный корень","awk");
        add("math.pow","Степень","awk");
        add("math.sin","Синус","awk");
        add("math.cos","Косинус","awk");
        add("math.tan","Тангенс","awk");
        add("math.log","Логарифм","awk");
        add("math.exp","Экспонента","awk");
        add("math.floor","Округление вниз","awk");
        add("math.ceil","Округление вверх","awk");
        add("math.random","Случайное число","awk");
        add("math.hex","Число в hex","printf '%x\\n'");
        add("math.octal","Число в octal","printf '%o\\n'");
        add("math.binary","Двоичное представление","echo 'binary conversion via shell'");
        add("diag.summary","Общая диагностика","id; uname -a; date; df -h .");
        add("diag.cpu","Диагностика CPU","cat /proc/cpuinfo | head -n 40");
        add("diag.memory","Диагностика памяти","cat /proc/meminfo | head -n 40");
        add("diag.process","Диагностика процесса","cat /proc/self/status | head -n 50");
        add("diag.fds","Открытые дескрипторы","ls -la /proc/$$/fd 2>/dev/null");
        add("diag.mounts","Проверка mount","cat /proc/mounts");
        add("diag.storage","Проверка диска","df -h");
        add("diag.guest","Проверка гостевого дерева","find . -maxdepth 2 -print");
        add("diag.system","Проверка system tree","ls -la /system 2>/dev/null");
        add("diag.vendor","Проверка vendor tree","ls -la /vendor 2>/dev/null");
        add("diag.dev","Проверка устройств","ls -la /dev | head -n 80");
        add("diag.proc","Проверка procfs","ls -la /proc | head -n 80");
        add("diag.sys","Проверка sysfs","ls -la /sys | head -n 80");
        add("diag.props","Проверка properties","getprop | head -n 120");
        add("diag.network","Проверка сети","ip addr 2>&1 | head -n 100");
        add("diag.dns","Проверка DNS props","getprop | grep -i dns");
        add("diag.battery","Состояние батареи","dumpsys battery 2>&1");
        add("diag.display","Сведения о дисплее","wm size 2>&1; wm density 2>&1");
        add("diag.activity","Сведения ActivityManager","dumpsys activity activities 2>&1 | head -n 100");
        add("diag.package","Сведения PackageManager","pm list packages 2>&1 | head -n 100");
        add("diag.services","Список сервисов","service list 2>&1 | head -n 100");
        add("diag.selinux","Состояние SELinux","getenforce 2>&1");
        add("diag.security","Security properties","getprop | grep -i security");
        add("diag.permissions","Проверка доступа","id; ls -ld .");
        add("diag.health","Быстрый health-check","echo ok; id; date");
    }
    private static void add(String name,String description,String target){COMMANDS.put(name,new Command(name,description,target));}
    public static boolean isKnown(String name){return COMMANDS.containsKey(name);}
    public static String execute(String name,String arguments){
        Command c=COMMANDS.get(name); if(c==null)return null;
        String a=arguments==null?"":arguments.trim();
        if(a.isEmpty())return c.target;
        return c.target+" "+a;
    }
    public static String help(String filter){
        String f=filter==null?"":filter.trim().toLowerCase(Locale.ROOT);
        StringBuilder out=new StringBuilder("Ayurones VM — 350 terminal commands\nFormat: command [arguments]\n\n");
        int shown=0;
        for(Command c:COMMANDS.values()){
            if(!f.isEmpty()&&!c.name.toLowerCase(Locale.ROOT).contains(f)&&!c.description.toLowerCase(Locale.ROOT).contains(f))continue;
            out.append(String.format(Locale.ROOT,"%-22s %s%n",c.name,c.description)); shown++;
        }
        out.append("\nПоказано: ").append(shown).append(" из 350");
        return out.toString();
    }
    private CommandCatalog(){}
}
