plugins { id 'com.android.application' }

android {
    namespace 'ai.ayurones.messenger'
    compileSdk 36

    defaultConfig {
        applicationId 'ai.ayurones.messenger'
        minSdk 26
        targetSdk 36
        versionCode 20
        versionName '0.2.0'
    }

    buildTypes {
        release { minifyEnabled false }
    }
}
